# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image:
#  name: $DOCKER_NAME
#  username: $DOCKER_USERNAME
#  password: $DOCKER_PASSWORD
#  email: $DOCKER_EMAIL

pipelines:
  default:
    - step:
        name: Deploy to Github
        script:
          - git push git@github.com:wisnet/five.git
